"""audit due dates templates activity

Revision ID: 88e5ba647445
Revises: 1c652ac72adb
Create Date: 2026-02-04 13:56:05.085039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e5ba647445'
down_revision: Union[str, Sequence[str], None] = '1c652ac72adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('audit_logs', sa.Column('user_id', sa.Integer(), nullable=True))
#     op.add_column('audit_logs', sa.Column('entity', sa.String(), nullable=False))
#     op.add_column('audit_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
#     op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(), nullable=True))
#     op.alter_column('audit_logs', 'action',
#                existing_type=sa.VARCHAR(),
#                nullable=False)
#     op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
#     op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
#     op.drop_column('audit_logs', 'admin_email')
#     op.add_column('todos', sa.Column('due_date', sa.Date(), nullable=True))
#     # ### end Alembic commands ###

def upgrade() -> None:
    # ---- AUDIT LOG FIX (SAFE) ----

    # 1. Add column as NULLABLE
    op.add_column(
        "audit_logs",
        sa.Column("entity", sa.String(), nullable=True)
    )

    # 2. Backfill existing rows
    op.execute(
        "UPDATE audit_logs SET entity = 'unknown' WHERE entity IS NULL"
    )

    # 3. Enforce NOT NULL after data is safe
    op.alter_column(
        "audit_logs",
        "entity",
        nullable=False
    )

    # ---- TODOS: DUE DATE ----
    op.add_column(
        "todos",
        sa.Column("due_date", sa.Date(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'due_date')
    op.add_column('audit_logs', sa.Column('admin_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity')
    op.drop_column('audit_logs', 'user_id')
    # ### end Alembic commands ###
